source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "image_optim"
gem "jekyll"
gem 'jekyll-archives'
gem "jekyll-assets"
gem "jekyll-twitter-plugin"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "sprockets"
gem "uglifier"
